
name: Build and Deploy Express App to K8s

on:
  push:
    branches:
      - main # Triggers the pipeline whenever code is pushed to the main branch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1. CHECKOUT SOURCE CODE
      - name: Checkout Source Code
        uses: actions/checkout@v5

      # 2. LOGIN TO GITHUB CONTAINER REGISTRY (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions

      # 3. BUILD AND PUSH DOCKER IMAGE
      - name: Convert repository to lowercase
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      

          # STEP 2: Build the fresh container image and tag it with the unique commit SHA
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/prashantubale2019/cicd-github:${{ github.sha }}
            ghcr.io/prashantubale2019/cicd-github:latest

      # STEP 3: Replace the old image text placeholder with the newly created image tag
      - name: Update Kubernetes Manifest Image Tag
        run: |
          sed -i "s|image: node-app:v1.0.0|image: ghcr.io/prashantubale2019/cicd-github:${{ github.sha }}|g" k8s/pipeline.yaml

      # 4. SETUP KUBECTL CLI
      - name: Setup Access to Kubernetes Cluster
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBERNETES_KUBECONFIG }}

      # 6. DEPLOY FRESH MANIFESTS TO CLUSTER
      - name: Deploy Manifests to Cluster
        run: |
          kubectl apply -f k8s/pipeline.yaml
          kubectl rollout status deployment/node-app-deployment
