 
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

name: Local Tool Kubernetes Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # 💡 CHANGE THIS LINE: Tells GitHub to run this job directly on your Mac terminal
    runs-on: self-hosted 

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # 1. BUILD YOUR LOCAL IMAGE FRESH
      - name: Build Local Image Cache
        run: |
          docker build -t node-app:latest .

      # 2. RUN DEPLOYMENT FREELY INSIDE YOUR MACHINE ENVIRONMENT
      - name: Deploy Manifests to Local Cluster
        run: |
          # Explicitly set image policy to look internally
          sed -i '' "s|imagePullPolicy: IfNotPresent|imagePullPolicy: Never|g" k8s/deployment.yaml
          
          kubectl apply -f k8s/
          kubectl rollout restart deployment/node-app-deployment
          kubectl rollout status deployment/node-app-deployment


      # 3. COMPILE AND PUSH IMMUTABLE PRODUCTION IMAGE
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # 4. INSTANTIATE KUBECTL CLIENT USING STORAGE SECRET
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_DATA }}

      # 5. INJECT UNIQUE SHA TAG INTO THE MANIFESTS
      - name: Update Deployment Manifest Image Tag
        run: |
          sed -i "s|image: node-app:latest|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" k8s/deployment.yaml
          sed -i "s|imagePullPolicy: Never|imagePullPolicy: Always|g" k8s/deployment.yaml

      # 6. EXECUTE FRESH ROLLOUT AND BYPASS SELF-SIGNED SSL
      - name: Deploy Manifests to Kubernetes
        run: |
          # The flag tells kubectl to ignore the untrusted local certificate
          kubectl apply -f k8s/ --insecure-skip-tls-verify=true
          kubectl rollout status deployment/node-app-deployment --insecure-skip-tls-verify=true
          --validate=false
          